---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7.2
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[xymon::default]
    attributes:
      xymon:
        servers: ["server1", "server2"]
